[package]
name = "fot-save-edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
byteorder = "1.4.3"
deflate = "1.0.0"
encoding_rs = "0.8.33"
inflate = "0.4.5"
memmem = "0.1.1"
